#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  group: services
  project: trustbloc

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- behavior: merge
  envs:
  - ucis/config.env
  name: ucis-comparator-env
- behavior: merge
  envs:
  - cbp/config.env
  name: cbp-comparator-env
- behavior: merge
  envs:
  - benefits-dept/config.env
  name: benefits-dept-comparator-env


secretGenerator:
- behavior: merge
  envs:
  - ucis/secret.env
  name: ucis-comparator-env-secret
- behavior: merge
  envs:
  - cbp/secret.env
  name: cbp-comparator-env-secret
- behavior: merge
  envs:
  - benefits-dept/secret.env
  name: benefits-dept-comparator-env-secret

resources:
- ../ucis
- ../cbp
- ../benefits-dept

transformers:
- sedtransform.yml
- sedb64transform.yml
