#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: svceng
kind: SedB64Transformer
metadata:
  name: sedb64transformer
argsOneLiner: s^||MONGODB_DSN||^${MONGODB_DSN}^
