#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
# Copyright Avast Software. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

commonLabels:
  component: issuer

configMapGenerator:
- envs:
  - config.env
  name: issuer-env
- files:
  - profiles-mapping.json
  name: issuer-profiles-mapping-config

secretGenerator:
- envs:
  - secret.env
  name: issuer-env-secret

resources:
- deployment.yml
- service.yml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: sandbox-issuer
  newName: ghcr.io/trustbloc-cicd/sandbox-issuer
  newTag: 0.1.9-snapshot-bc094bb
